<a href="https://colab.research.google.com/github/sojuvarghese22/PyTorch/blob/main/linear_regression(gradient).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import torch
# Input (temp, rainfall, humidity)
inputs = np.array([[73, 67, 43], 
                   [91, 88, 64], 
                   [87, 134, 58], 
                   [102, 43, 37], 
                   [69, 96, 70]], dtype='float32')
targets = np.array([[56, 70], 
                    [81, 101], 
                    [119, 133], 
                    [22, 37], 
                    [103, 119]], dtype='float32')
# Convert inputs and targets to tensors
inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)
print(inputs)
print(targets)

tensor([[ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.]])
tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])


In [2]:
# Weights and biases
w = torch.randn(2, 3, requires_grad=True)
b = torch.randn(2, requires_grad=True)
print(w)
print(b)


tensor([[ 1.7198, -0.9226,  1.0296],
        [-0.9275, -1.2857,  0.2453]], requires_grad=True)
tensor([0.8856, 1.1846], requires_grad=True)


In [3]:
def model(x):
    return x @ w.t() + b

In [4]:
preds = model(inputs)
print(preds)

tensor([[ 108.8921, -142.1190],
        [ 142.0963, -180.6634],
        [  86.6005, -237.5667],
        [ 174.7310, -139.6315],
        [ 103.0575, -169.0722]], grad_fn=<AddBackward0>)


In [5]:
# Compare with targets
print(targets)

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])


In [8]:
diff = targets-preds

In [10]:
targets-preds

tensor([[ 58.1628,  -9.5187],
        [ 72.8502,   5.5730],
        [124.9105,   0.3217],
        [ 40.7257, -51.9981],
        [ 78.5848,  39.8481]], grad_fn=<SubBackward0>)

In [9]:
torch.sum(diff*diff)/diff.numel()

tensor(40673.9492, grad_fn=<DivBackward0>)

In [10]:
# MSE loss
def mse(t1, t2):
    diff = t1 - t2
    return torch.sum(diff * diff) / diff.numel()

In [11]:
# Compute loss
loss = mse(preds, targets)
print(loss)

tensor(40673.9492, grad_fn=<DivBackward0>)


In [12]:
loss.backward()

In [13]:
print(w)
print(w.grad)

tensor([[ 1.7198, -0.9226,  1.0296],
        [-0.9275, -1.2857,  0.2453]], requires_grad=True)
tensor([[  4436.9316,   2230.3333,   1992.0848],
        [-22249.7520, -24780.8750, -15068.1719]])


In [15]:
w.grad

tensor([[-6263.7686, -7268.2168, -4283.2026],
        [  542.8065,  -297.0536,  -166.2914]])

In [14]:
with torch.no_grad():
    w -= w.grad * 1e-5
    b -= b.grad * 1e-5

In [15]:
# Let's verify that the loss is actually lower
loss = mse(preds, targets)
print(loss)

tensor(40673.9492, grad_fn=<DivBackward0>)


In [16]:
w.grad.zero_()
b.grad.zero_()
print(w.grad)
print(b.grad)

tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([0., 0.])


In [20]:
# Generate predictions
preds = model(inputs)
print(preds)

tensor([[ 103.3018, -102.7915],
        [ 134.8206, -128.9626],
        [  78.5959, -176.2608],
        [ 168.5087, -100.7031],
        [  96.4599, -119.3799]], grad_fn=<AddBackward0>)


In [21]:
# Calculate the loss
loss = mse(preds, targets)
print(loss)

tensor(28244.3320, grad_fn=<DivBackward0>)


In [ ]:
# Compute gradients
loss.backward()
print(w.grad)
print(b.grad)

In [ ]:
with torch.no_grad():
    w -= w.grad * 1e-5
    b -= b.grad * 1e-5
    w.grad.zero_()
    b.grad.zero_()

In [ ]:
print(w)
print(b)

In [ ]:
# Calculate loss
preds = model(inputs)
loss = mse(preds, targets)
print(loss)

In [28]:
for i in range(200):
    preds = model(inputs)
    loss = mse(preds, targets)
    loss.backward()
    with torch.no_grad():
        w -= w.grad * 1e-5
        b -= b.grad * 1e-5
        w.grad.zero_()
        b.grad.zero_()

In [29]:
# Calculate loss
preds = model(inputs)
loss = mse(preds, targets)
print(loss)

tensor(15.4970, grad_fn=<DivBackward0>)


In [30]:
preds

tensor([[ 58.2762,  70.7832],
        [ 85.2441, 102.1341],
        [110.0020, 128.8707],
        [ 26.9254,  38.7253],
        [103.9651, 120.9221]], grad_fn=<AddBackward0>)

In [25]:
targets

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])